version: 0.2
env:
  variables:
    TF_VERSION: "0.15.5"

phases:

  install:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  build:
    commands:
      - mkdir -p /codebuild/terraform
      - rm -rf /codebuild/terraform/*
      - cp -r ./* /codebuild/terraform/
      - cd /codebuild/terraform/terraform
      - ls
      - terraform init
      #- terraform apply -auto-approve